serverHost: "0.0.0.0"
serverPort: 9090
workerThreads: 4
searchThreads: 4
maxContentLength: 1048576
indexPath: "./data"
clusterName: "nexo-cluster"
nodeName: "nexo-node-1"

vectorIndex:
  dimension: 1024
  metric: "cos"
  connectivity: 16
  expansionAdd: 200
  expansionSearch: 200
  quantization: "f32"

embedding:
  model: "nomic"
  url: "http://localhost:11434"

keywordIndex:
  defaultAnalyzer: "standard"
  stemming: true
  stopWords: true
  caseSensitive: false
