unstable_features = true
combine_control_expr = false
imports_layout = "HorizontalVertical"
match_block_trailing_comma = true
max_width = 89
comment_width = 120
format_strings = true
group_imports = "StdExternalCrate"
imports_granularity = "Module"
normalize_comments = true
where_single_line = true
wrap_comments = true