name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  format-check:
    name: Format Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Check Java formatting
        run: mvn fmt:check

      - name: Set up Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt

      - name: Check Rust formatting
        run: cargo fmt --check --manifest-path src/main/rust/Cargo.toml

  build-java:
    name: Build Java
    runs-on: ubuntu-latest
    needs: format-check
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B clean compile --file pom.xml

      - name: Run tests
        run: mvn -B test

  build-rust:
    name: Build Rust
    runs-on: ubuntu-latest
    needs: format-check
    steps:
      - uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Build Rust library
        run: cargo build --release --manifest-path src/main/rust/Cargo.toml

      - name: Run Rust tests
        run: cargo test --manifest-path src/main/rust/Cargo.toml

  integration-test:
    name: Integration Tests
    runs-on: ubuntu-latest
    needs: [build-java, build-rust]
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Set up Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Build and run integration tests
        run: |
          cargo build --release --manifest-path src/main/rust/Cargo.toml
          mvn -B verify
